name: "Run Tests"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install codecov
        pip install pytest-cov
        pip install .

    - name: Run tests
      run: |
        pytest --cov=./ --cov-report=xml

  codecov:
    needs: tests
    runs-on: ubuntu-22.04

    steps:
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      With:
        file: ./coverage.xml
        directory: ./coverage/reports/
        flags: unittests
        env_vars: OS,PYTHON
        name: codecov-umbrella
        fail_ci_if_error: true
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true

      # env:
      #   CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}