name: PR Examples

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
    paths:
      - "tutorials/**"
      - "dlordinal/**"
      - ".github/workflows/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  run-notebook-tutorials:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install notebook
          pip install jupyterlab

      - name: Grant execute permissions to run_tutorials.sh
        run: chmod +x build_tools/run_tutorials.sh

      - name: Run example notebooks
        run: build_tools/run_tutorials.sh
        shell: bash